sudo: false

language: python
python:
  - "2.7"

os:
  - linux

env:
    global:
        - secure: "l/4Dt+KQ/mACtGAHDUsPr66fUte840PZoQ4xpPikqWZI0uARu4l+Ym7+sHinnT6fBqrj8AJeBYGz4nFa8NK4LutZn9mSD40w+sxl0wSV4oHV8rzKe3Cd8+sMG3+o33yWoikMNjSvqa73Q0rm+SgrlInNdZbuAyixL+a2alaWSnGPm4F2xwUGj+S33TOy5P/Xp77CYtCV5S8vzyk/eEdNhoF0GYePJVdfuzCOUjXMyT5OWxORkzzQ7Hnn/Ka/RDfV8Si4HgujLQBrK5q6iPnNBFqBSqilYBepSMn4opnOBpIm0SCgePz7XQEFC83buA7GUcnCnfg38bf+dCwHaODf1d1PmqVRYt2QmfinexXtM4afAtL0iBUDtvrfnXHzwW9w82VeZhpbJSVh9DUQvB0IlsZeCz9J9PUBAi3N+SMX+9l+BomYwRUlPuKY+Ef2JKk9q6mxtUkky5R0daAlVxEhpVdQks1rT+T+NMoDMemxQ3SKEiqAHh6EgHecruszffmZ71uLX9MpERpew0qN+UFiafws+jkTjx+3yF9yut0Hf9sMbeAYzzkGzRqJTUEBJ6B29Cql8M0yRXCNN/8wuuTHhG8esstozga4ZQoIVrq7mEAgup376PTcNfr1+imbbWVQ7lJdYIuDe6OS5V3OX6np11vgK/DbhfyzvQv9Z1zAGnM="
        - REMOTE_URL=https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG
    
script:
  #- set -e
  - echo -e "travis_fold:start:sketch_test_env_prepare"
  - pip install pyserial
  - wget -O arduino.tar.xz https://www.arduino.cc/download.php?f=/arduino-nightly-linux64.tar.xz
  - tar xf arduino.tar.xz
  - mv arduino-nightly $HOME/arduino_ide
  - mkdir -p $HOME/Arduino/libraries
  - cd $HOME/arduino_ide/hardware
  - mkdir espressif
  - cd espressif
  - ln -s $TRAVIS_BUILD_DIR esp32
  - cd esp32
  - git submodule update --init --recursive
  - cd tools
  - python get.py
  - export PATH="$HOME/arduino_ide:$TRAVIS_BUILD_DIR/tools/xtensa-esp32-elf/bin:$PATH"
  - which arduino
  - cd $TRAVIS_BUILD_DIR
  - source tools/common.sh
  - echo -e "travis_fold:end:sketch_test_env_prepare"
  - echo -e "travis_fold:start:sketch_test"
#  - build_sketches $HOME/arduino_ide $TRAVIS_BUILD_DIR/libraries "-l $HOME/Arduino/libraries"
  - echo -e "travis_fold:end:sketch_test"
  - echo -e "travis_fold:start:size_report"
#  - cat size.log
  - echo -e "travis_fold:end:size_report"

  # test library examples with PlatformIO
  - echo -e "travis_fold:start:platformio_test_env_prepare"
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install https://github.com/Nefry-Community/platform-espressif32.git#feature/support_nefry
#  - sed -i 's/https:\/\/github\.com\/Nefry-Community\/arduino-esp32\.git/*/' ~/.platformio/platforms/espressif32_stage/platform.json
  - ln -s $TRAVIS_BUILD_DIR ~/.platformio/packages/framework-arduinoespressif32
  - echo -e "travis_fold:end:platformio_test_env_prepare"
  - echo -e "travis_fold:start:platformio_test"
  - "python -c \"import glob,os,subprocess,sys; map(lambda p: (sys.stdout.write('Library example: %s\\n' % p), subprocess.call(['pio', 'ci', p, '--board', 'esp32dev'])), set([os.path.dirname(p) for p in glob.glob('libraries/*/examples/*/*.ino') + glob.glob('libraries/*/examples/*/*/*.ino')]))\""
  - echo -e "travis_fold:end:platformio_test"

notifications:
  email:
    on_success: change
    on_failure: change
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always